app:
    resource: '@AppBundle/Controller/'
    type: annotation

register:
    path: /register
    defaults: { _controller: AppBundle:Login:register, _format: html }
    requirements:
        _method: GET

home:
    path: /home
    defaults: { _controller: AppBundle:Home:getHome, _format: html }
    requirements:
        _method: GET

add:
    path: /add
    defaults: { _controller: AppBundle:Post:addPost, _format: html }
    requirements:
        _method: GET

  