# AppBundle\Entity\User:
#     type: entity
#     table: null
#     repositoryClass: AppBundle\Repository\UserRepository
#     id:
#         id:
#             type: integer
#             id: true
#             generator:
#                 strategy: AUTO
#     fields:
#         login:
#             type: string
#             length: 255
#             unique: true
#         password:
#             type: string
#             length: 255
#         plainPassword:
#             type: string
#             length: 255
#     lifecycleCallbacks: {  }


AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO